<?php
$form = $this->form;
$form->prepare();
?>
<h2>Novo Equipamento</h2>
<?php if($this->msg): ?>
    <div class="alert alert-success"><?php echo $this->msg ?></div>
<?php endif; ?>
<p class="text-right"><a href="<?php echo $this->url('equipamentos') ?>" class="btn btn-default">Voltar</a></p>
<?php echo $this->form()->openTag($form) ?>
<div class="form-group">
    <label><?php echo $this->formLabel($form->get('sigla')); ?>:</label>
    <?php echo $this->formElement()->render($form->get('sigla')) ?>
</div>
<div class="form-group">
    <label><?php echo $this->formLabel($form->get('marca')); ?>:</label>
    <?php echo $this->formElement()->render($form->get('marca')) ?>
</div>
<div class="form-group">
    <label><?php echo $this->formLabel($form->get('modelo')); ?>:</label>
    <?php echo $this->formElement()->render($form->get('modelo')) ?>
</div>
<div class="form-group">
    <label><?php echo $this->formLabel($form->get('cliente')); ?>:</label>
    <?php echo $this->formElement()->render($form->get('cliente')) ?>
</div>
<div class="form-group">
    <label><?php echo $this->formLabel($form->get('local_atual')); ?>:</label>
    <?php echo $this->formElement()->render($form->get('local_atual')) ?>
</div>
<div class="form-group">
    <label><?php echo $this->formLabel($form->get('descricao')); ?>:</label>
    <?php echo $this->formElement()->render($form->get('descricao')) ?>
</div>
<div class="form-group">
    <label><?php echo $this->formLabel($form->get('observacao')); ?>:</label>
    <?php echo $this->formElement()->render($form->get('observacao')) ?>
</div>
<div class="form-group">
    <label><?php echo $this->formLabel($form->get('data_aquisicao')); ?>:</label>
    <?php echo $this->formElement()->render($form->get('data_aquisicao')) ?>
</div>
<div class="form-group">
    <label><?php echo $this->formLabel($form->get('identificacao')); ?>:</label>
    <?php echo $this->formElement()->render($form->get('identificacao')) ?>
</div>
<div class="form-group">
    <label><?php echo $this->formLabel($form->get('acessorios')); ?>:</label>
    <?php echo $this->formElement()->render($form->get('acessorios')) ?>
</div>
<div class="form-group">
    <label><?php echo $this->formLabel($form->get('disponivel')); ?>:</label>
    <?php echo $this->formElement()->render($form->get('disponivel')) ?>
</div>
<div class="form-group">
    <label><?php echo $this->formLabel($form->get('funcionarios_id')); ?>:</label>
    <?php echo $this->formElement()->render($form->get('funcionarios_id')) ?>
</div>


<?php echo $this->formElement()->render($form->get('salvar')) ?>
<?php echo $this->form()->closeTag() ?>
